export const ROUTER = {
  USER: {
    HOME: "/home",
    PROFILE: "/profile",
    DETAIL_COURT: "/courts/:courtId",
    SCHEDULE_COURT: "/court-schedule/:courtId",
    COURT_BOOKING_CONFIRMATION: "/booking-confirmation",
    COURT_BOOKING_SUMMARY: "/booking-summary",
    COACH_BOOKING_HISTORY: "/coach-booking-history",
    COURT_HOMEPAGE: "/court/:type",
    COACH_GET_ALL: "/coaches/:type",
    COACH_GET_ALL_DEFAULT: "/coaches",
    COACH_GET_DETAIL: "/coaches/profile/:coachId",
    PRIVACY_POLICY: "/privacy-policy",
    ABOUT_US: "/about-us",
    SUPPORT_CENTER: "/support-center",
    BLOG: "/blog",
    CHAT: "/chat/:coachId",
    ROOM: "/room",
    COACH_BOOKING_SELECT_COURT: "/coach-booking/:coachId/court-selector/:type",
    COURT_BOOKING_HISTORY: "/court-booking-history",
    PAYMENT_SUCCESS: "/payment-success",
    PAYMENT_FAIL: "/payment-fail",
  },
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
  },
  OTP_VERIFICATION: "/verify-otp",
  OWNER: {
    HOME: "/owner",
    OWNERPROFILE: "/ownerProfile",
    HUMANHABITS: "/owner/humanhabits",
    PITCHHISTORY: "/owner/pitchhistory",
    BOOKINGMANAGEMENT: "/owner/bookingmanagement",
    REVIEWYARD: "/owner/reviewyard",
    SportsComplexes: "/owner/sportscomplexes",
    SportsComplexDetail: "/owner/sportscomplexes/:id",
    CourtDetailOwner: "/owner/CourtDetailOwner/:courtId",
    CreateSportsComplexes: "/owner/CreateSportsComplexes",
    CREATE_COURT: "/owner/createcourt/:sportsComplexId", // thêm param sportsComplexId
  },
  COACH: {
    HOME: "/coach",
    CHAT: "/coach/chat",
    REVIEWCOACH: "/coach/reviewCoach",
    COACHHISTORY: "/coach/CoachHistory",
    PROFILEBYCOACH: "/coachProfile",
  },
};
